apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: demo-with-docker-v1
        name: demo-with-docker
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
        readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
        livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 1
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: default
spec:
  ports:
  - name: 8080-8080
    port: 8080
    targetPort: 8080
  selector:
    app: demo
  type: LoadBalancer
